server:
  port: 8081

spring:
  application:
    name: Panalitix


  # Configuração do Banco de Dados
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Configuração do JPA / Hibernate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Configuração do Flyway (Migrations)
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# Configurações Customizadas para o JWT (Seu TokenService)
api:
  security:
    token:
      # Use uma chave longa e complexa. Em produção, use variável de ambiente!
      secret: ${JWT_SECRET}
      expiration: 86400000 # 24 horas em ms
      issuer: "Bet Analytix API"